# Numpy Medium Level 25 quetions based on  midlevel topics

| #  | Topic          | Problem                                                 |
| -- | -------------- | ------------------------------------------------------- |
| 26 | Conditional    | Replace negative numbers with their absolute value      |
| 27 | Normalization  | Normalize array values between 0 and 1                  |
| 28 | Broadcasting   | Subtract each column mean from the matrix               |
| 29 | Statistics     | Compute row-wise mean and std deviation                 |
| 30 | Aggregation    | Sum along rows and columns separately                   |
| 31 | Unique         | Find unique elements and their counts                   |
| 32 | Cumulative     | Compute cumulative sum and product                      |
| 33 | Correlation    | Find correlation coefficient between two arrays         |
| 34 | Linear Algebra | Compute matrix multiplication using `@` and `dot()`     |
| 35 | Linear Algebra | Compute determinant and inverse of a matrix             |
| 36 | Linear Algebra | Verify that `A @ inv(A)` = Identity matrix              |
| 37 | Linear Algebra | Solve linear system `Ax = b`                            |
| 38 | Random         | Create reproducible random numbers using seed           |
| 39 | Random         | Generate normal distribution (mean=0, std=1, size=1000) |
| 40 | Random         | Simulate 10 dice rolls (1–6) and count frequencies      |
| 41 | Vectorization  | Replace all loops with NumPy vectorized ops             |
| 42 | Broadcasting   | Add 1D array to 2D using broadcasting rules             |
| 43 | Distance       | Compute Euclidean distance between two vectors          |
| 44 | Angle          | Compute cosine similarity between two vectors           |
| 45 | Reshape        | Create 3D array and reshape it to 2D                    |
| 46 | Axis Ops       | Find index of max per row and per column                |
| 47 | Replace        | Replace all NaN values with column mean                 |
| 48 | Insert         | Insert a new column into a 2D array                     |
| 49 | Split & Merge  | Split an array vertically and then merge back           |
| 50 | Logic          | Check if any element > 100 or all elements > 0          |


# Conditional Absolute values
#### 26. Replace negative numbers with their absolute value

In [1]:
import numpy as np
arr = np.array([-1, 2, -3, 4])
arr = np.abs(arr)
print(arr)

[1 2 3 4]


# Normalize
#### 27. Normalize array values between 0 and 1

In [2]:
arr = np.array([10, 20, 30])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)


[0.  0.5 1. ]


# Broadcasting
#### 28. Subtract each column mean from the matrix

In [3]:
mat = np.array([[1,2],[3,4],[5,6]])
col_mean = mat.mean(axis=0)
print("mean ",col_mean)
result = mat - col_mean
print("Subtract each column with mean\n",result)

mean  [3. 4.]
Subtract each column with mean
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


# Statistics
#### 29. Compute row-wise mean and std deviation

In [4]:
mat = np.array([[1,2,3],[4,5,6]])
row_mean = mat.mean(axis=1)
row_std = mat.std(axis=1)
print(row_mean, row_std)

[2. 5.] [0.81649658 0.81649658]


# Aggregation
#### 30. Sum along rows and columns separately

In [5]:
mat = np.array([[1,2,3],[4,5,6]])
row_sum = mat.sum(axis=1)
col_sum = mat.sum(axis=0)
print(row_sum, col_sum)


[ 6 15] [5 7 9]


# Unique
#### 31. Find unique elements and their counts

In [6]:
arr = np.array([1,2,2,3,3])
unique, counts = np.unique(arr, return_counts=True)
print(unique, counts)

[1 2 3] [1 2 2]


# Cumulative
#### 2. Compute cumulative sum and product

In [7]:
arr = np.array([1,2,3,4])
cumsum = np.cumsum(arr)
cumprod = np.cumprod(arr)
print(cumsum, cumprod)

[ 1  3  6 10] [ 1  2  6 24]


# Correlation
#### 33. Find correlation coefficient between two arrays

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
corr = np.corrcoef(a, b)[0,1]
print(corr)


1.0


# Linear Algebra
#### 34. Compute matrix multiplication using @ and dot()

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A @ B)
print(A.dot(B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### 35. Compute determinant and inverse of a matrix

In [10]:
A = np.array([[1,2],[3,4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
print(det) 
print(inv)


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


#### 36. Verify that A @ inv(A) = Identity matrix

In [11]:
A = np.array([[1,2],[3,4]])
inv = np.linalg.inv(A)
identity = np.round(A @ inv, decimals=10)
print(identity)


[[1. 0.]
 [0. 1.]]


#### 37. Solve linear system Ax = b

In [12]:
A = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(A, b)
print(x)


[2. 3.]


# Random
#### 38. Create reproducible random numbers using seed

In [13]:
np.random.seed(42) ## same random nums will reproduce every execution
rand_nums = np.random.rand(5)
print(rand_nums)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


#### 39. Generate normal distribution (mean=0, std=1, size=1000)

In [14]:
norm_dist = np.random.normal(0, 1, 1000) # mean is 0 and 1 is std and size is 1000 elements to generate normal dist
print(norm_dist[:10])  # first 10 values

[ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017 -0.92408284
 -2.61254901  0.95036968  0.81644508 -1.523876  ]


#### 40. Simulate 10 dice rolls (1–6) and count frequencies

In [15]:
import numpy as np

# Simulate dice rolls
rolls = np.random.randint(1, 7, 10)

# Count occurrences
unique, counts = np.unique(rolls, return_counts=True)

# Convert to plain int dictionary for readability
counts_dict = {int(u): int(c) for u, c in zip(unique, counts)}

print("Rolls:", rolls)
print("Counts:", counts_dict)


Rolls: [2 6 3 2 6 4 4 5 1 5]
Counts: {1: 1, 2: 2, 3: 1, 4: 2, 5: 2, 6: 2}


# Vectorization
#### 41. Replace all loops with NumPy vectorized ops

In [16]:
# Example: add 2 to each element
arr = np.array([1,2,3])
arr = arr + 2
print(arr)

[3 4 5]


# broadcasting rules 
#### 42. Add 1D array to 2D using broadcasting rules

In [17]:
mat = np.array([[1,2,3],[4,5,6]])   # (2,3)
arr = np.array([10,20,30])  # (3,)  -> (1,3)
result = mat + arr   
print(result)

[[11 22 33]
 [14 25 36]]


# Distance
#### 43. Compute Euclidean distance between two vectors

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
dist = np.linalg.norm(a - b)
print(dist)

5.196152422706632


# Angle
#### 44. Compute cosine similarity between two vectors

In [19]:

a = np.array([1,2,3])
b = np.array([4,5,6])
cos_sim = np.dot(a,b) / (np.linalg.norm(a)*np.linalg.norm(b))
print(cos_sim)

0.9746318461970762


# Reshape
#### 45. Create 3D array and reshape it to 2D

In [20]:

arr3d = np.arange(24).reshape(2,3,4)
arr2d = arr3d.reshape(2,12)
print(arr2d)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


# Axis Ops 
#### 46. Find index of max per row and per column

In [21]:

mat = np.array([[1,4,2],[5,0,3]])
row_max_idx = np.argmax(mat, axis=1)
col_max_idx = np.argmax(mat, axis=0)
print(row_max_idx, col_max_idx)


[1 0] [1 0 1]


# Mean
#### 47. Replace all NaN values with column mean

In [22]:

mat = np.array([[1, np.nan],[3, 4]])
col_mean = np.nanmean(mat, axis=0)
inds = np.where(np.isnan(mat))
mat[inds] = np.take(col_mean, inds[1])
print(mat)

[[1. 4.]
 [3. 4.]]


# New col Insert
#### 48. Insert a new column into a 2D array

In [23]:

mat = np.array([[1,2],[3,4]])
new_col = np.array([[9],[10]])
mat_new = np.hstack((mat, new_col))
print(mat_new)


[[ 1  2  9]
 [ 3  4 10]]


# Split & Merge
#### 49. Split an array vertically and then merge back

In [24]:

mat = np.arange(16).reshape(4,4)
split = np.vsplit(mat, 2)
merged = np.vstack(split)
print(merged)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Logic
#### 50. Check if any element > 100 or all elements > 0

In [25]:

arr = np.array([10,20,30])
any_gt_100 = np.any(arr > 100)
all_gt_0 = np.all(arr > 0)
print(any_gt_100, all_gt_0)

False True
