# NumPy Complete Implementation for AI/ML



## 1. Import NumPy

`np` is the standard alias. You may technically choose another valid alias, but `np` is the community convention.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## 2. Python List vs NumPy Array

NumPy arrays are designed for numerical computing and support vectorized operations.

In [3]:
python_list = [1, 2, 3, 4]
numpy_array = np.array([1, 2, 3, 4])

print("Python list:", python_list)
print("NumPy array:", numpy_array)
print("Array type:", type(numpy_array))

Python list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Array type: <class 'numpy.ndarray'>


## 3. Creating 1D, 2D and 3D Arrays

In [4]:
a1 = np.array([10, 20, 30, 40])
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D:\n", a1)
print("\n2D:\n", a2)
print("\n3D:\n", a3)

1D:
 [10 20 30 40]

2D:
 [[1 2 3]
 [4 5 6]]

3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 4. Important Array Attributes

In [6]:
for name, arr in [("a1", a1), ("a2", a2), ("a3", a3)]:
    print(
        name,
        "ndim =", arr.ndim,
        "shape =", arr.shape,
        "size =", arr.size,
        "dtype =", arr.dtype,
        "itemsize =", arr.itemsize,
        "bytes =", arr.nbytes
    )

a1 ndim = 1 shape = (4,) size = 4 dtype = int32 itemsize = 4 bytes = 16
a2 ndim = 2 shape = (2, 3) size = 6 dtype = int32 itemsize = 4 bytes = 24
a3 ndim = 3 shape = (2, 2, 2) size = 8 dtype = int32 itemsize = 4 bytes = 32


## 5. Data Types and Type Conversion

In [8]:
integers = np.array([1, 2, 3], dtype=np.int32)
floats = integers.astype(float)

print(integers, integers.dtype)
print(floats, floats.dtype)

[1 2 3] int32
[1. 2. 3.] float64


## 6. Array Creation Helpers

In [10]:
print("zeros:\n", np.zeros((2, 3)))
print("\nones:\n", np.ones((2, 3)))
print("\nfull:\n", np.full((2, 3), 7))
print("\nidentity:\n", np.eye(3))
print("\nempty (uninitialized values):\n", np.empty((2, 2)))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

full:
 [[7 7 7]
 [7 7 7]]

identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

empty (uninitialized values):
 [[0.0000000e+000 1.3342897e-311]
 [1.3342897e-311 1.3342897e-311]]


## 7. arange and linspace

In [12]:
print("arange:", np.arange(1, 11))
print("arange step 2:", np.arange(2, 21, 2))
print("linspace:", np.linspace(0, 10, 5))

arange: [ 1  2  3  4  5  6  7  8  9 10]
arange step 2: [ 2  4  6  8 10 12 14 16 18 20]
linspace: [ 0.   2.5  5.   7.5 10. ]


## 8. Random Numbers — Recommended Generator API

In [14]:
rng = np.random.default_rng(42)

print("Random floats:", rng.random(5))
print("Random integers:", rng.integers(1, 100, size=10))
print("Normal distribution:", rng.normal(loc=0, scale=1, size=5))
print("Choice:", rng.choice(["AI", "ML", "DL"], size=5))

Random floats: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random integers: [53 97 73 76 72 78 51 13 84 45]
Normal distribution: [0.87939797 0.77779194 0.0660307  1.12724121 0.46750934]
Choice: ['ML' 'AI' 'AI' 'ML' 'DL']


## 9. Indexing

In [16]:
arr = np.array([10, 20, 30, 40, 50])

print("First:", arr[0])
print("Fourth:", arr[3])
print("Last:", arr[-1])

matrix = np.array([[10, 20, 30], [40, 50, 60]])
print("matrix[0, 1] =", matrix[0, 1])
print("matrix[1, 2] =", matrix[1, 2])

First: 10
Fourth: 40
Last: 50
matrix[0, 1] = 20
matrix[1, 2] = 60


## 10. Slicing

In [61]:
arr = np.arange(1, 11)
print(arr)
print("arr[2:6] =", arr[2:6])
lis = [1,2,3,4,5,6]
print(lis)
print("lis",lis[2:6])
print("arr[2:6] =", arr[2:6])
print("arr[:5] =", arr[:5])
print("arr[4:] =", arr[4:])
print("arr[::2] =", arr[::2])
print("reverse =", arr[::-1])

matrix = np.arange(1, 13).reshape(3, 4)
print("\nMatrix:\n", matrix)
print("\nFirst row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Sub-matrix:\n", matrix[0:2, 1:3])

[ 1  2  3  4  5  6  7  8  9 10]
arr[2:6] = [3 4 5 6]
[1, 2, 3, 4, 5, 6]
lis [3, 4, 5, 6]
arr[2:6] = [3 4 5 6]
arr[:5] = [1 2 3 4 5]
arr[4:] = [ 5  6  7  8  9 10]
arr[::2] = [1 3 5 7 9]
reverse = [10  9  8  7  6  5  4  3  2  1]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Second column: [ 2  6 10]
Sub-matrix:
 [[2 3]
 [6 7]]


## 11. Reshape, Flatten, Ravel and Transpose

In [19]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print(arr)
print("Reshaped:\n", matrix)
print("Flatten:", matrix.flatten())
print("Ravel:", matrix.ravel())
print("Transpose:\n", matrix.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 12. reshape with -1

In [23]:
arr = np.arange(1, 13)
print(arr)
print(arr.reshape(2, -1))
print(arr.reshape(-1, 3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 13. Element-wise Arithmetic

In [25]:
a = np.array([1, 2, 3, 4])

print("a + 10:", a + 10)
print("a - 5:", a - 5)
print("a * 2:", a * 2)
print("a / 2:", a / 2)
print("a ** 2:", a ** 2)

a + 10: [11 12 13 14]
a - 5: [-4 -3 -2 -1]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]
a ** 2: [ 1  4  9 16]


## 14. Operations Between Arrays

In [26]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Element-wise multiplication:", a * b)
print("Division:", b / a)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Element-wise multiplication: [10 40 90]
Division: [10. 10. 10.]


## 15. Universal Functions (ufuncs)

In [28]:
a = np.array([1, 4, 9, 16], dtype=float)

print(arr)
print("sqrt:", np.sqrt(a))
print("square:", np.square(a))
print("power:", np.power(a, 3))
print("exp:", np.exp(np.array([0, 1, 2])))
print("log:", np.log(np.array([1, np.e, np.e**2])))
print("abs:", np.abs(np.array([-3, -1, 2])))
print("round:", np.round(np.array([1.234, 2.678]), 2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
sqrt: [1. 2. 3. 4.]
square: [  1.  16.  81. 256.]
power: [1.000e+00 6.400e+01 7.290e+02 4.096e+03]
exp: [1.         2.71828183 7.3890561 ]
log: [0. 1. 2.]
abs: [3 1 2]
round: [1.23 2.68]


## 16. Aggregation Functions

In [29]:
a = np.array([10, 20, 30, 40, 50])

print("sum:", np.sum(a))
print("mean:", np.mean(a))
print("median:", np.median(a))
print("min:", np.min(a))
print("max:", np.max(a))
print("std:", np.std(a))
print("variance:", np.var(a))
print("argmin:", np.argmin(a))
print("argmax:", np.argmax(a))

sum: 150
mean: 30.0
median: 30.0
min: 10
max: 50
std: 14.142135623730951
variance: 200.0
argmin: 0
argmax: 4


## 17. Aggregations by Axis

In [31]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print("Matrix:\n", m)
print("Column sums (axis=0):", m.sum(axis=0))
print("Row sums (axis=1):", m.sum(axis=1))
print("Column means:", m.mean(axis=0))
print("Row means:", m.mean(axis=1))

Matrix:
 [[1 2 3]
 [4 5 6]]
Column sums (axis=0): [5 7 9]
Row sums (axis=1): [ 6 15]
Column means: [2.5 3.5 4.5]
Row means: [2. 5.]


## 18. Broadcasting

In [33]:
m = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])

print("Matrix + row vector:\n", m + row)

col = np.array([[100], [200]])
print("\nMatrix + column vector:\n", m + col)

Matrix + row vector:
 [[11 22 33]
 [14 25 36]]

Matrix + column vector:
 [[101 102 103]
 [204 205 206]]


## 19. Boolean Indexing

In [35]:
a = np.array([10, 20, 30, 40, 50, 60])

mask = a > 30
print("Mask:", mask)
print("Values > 30:", a[mask])
print("Even and > 20:", a[(a % 2 == 0) & (a > 20)])

Mask: [False False False  True  True  True]
Values > 30: [40 50 60]
Even and > 20: [30 40 50 60]


## 20. np.where and np.select

In [36]:
scores = np.array([35, 55, 72, 88, 41])

result = np.where(scores >= 50, "Pass", "Fail")
print("where:", result)

conditions = [
    scores < 50,
    (scores >= 50) & (scores < 75),
    scores >= 75
]
choices = ["Fail", "Average", "Excellent"]

print("select:", np.select(conditions, choices, default="Unknown"))

where: ['Fail' 'Pass' 'Pass' 'Pass' 'Fail']
select: ['Fail' 'Average' 'Average' 'Excellent' 'Fail']


## 21. Sorting and Searching

In [37]:
a = np.array([50, 10, 40, 20, 30])

print("sort:", np.sort(a))
print("argsort:", np.argsort(a))
print("where a > 25:", np.where(a > 25)[0])

sort: [10 20 30 40 50]
argsort: [1 3 4 2 0]
where a > 25: [0 2 4]


## 22. Unique Values

In [39]:
a = np.array([1, 2, 2, 3, 3, 3, 4])

values, counts = np.unique(a, return_counts=True)
print("Unique:", values)
print("Counts:", counts)

Unique: [1 2 3 4]
Counts: [1 2 3 1]


## 23. Concatenate and Stack

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate((a, b)))
print("vstack:\n", np.vstack((a, b)))
print("hstack:", np.hstack((a, b)))
print("column_stack:\n", np.column_stack((a, b)))

concatenate: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
column_stack:
 [[1 4]
 [2 5]
 [3 6]]


## 24. Splitting Arrays

In [42]:
a = np.arange(1, 13)

print("split into 3:", np.split(a, 3))
print("array_split into 5:", np.array_split(a, 5))

split into 3: [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
array_split into 5: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


## 25. Copy vs View

In [47]:
original = np.array([1, 2, 3, 4])
print(original)

copied = original.copy()  
viewed = original.view()

copied[0] = 100
viewed[1] = 200

print("Original:", original)
print("Copy:", copied)
print("View:", viewed)

[1 2 3 4]
Original: [  1 200   3   4]
Copy: [100   2   3   4]
View: [  1 200   3   4]


## 26. Missing Values (NaN)

In [51]:
a = np.array([10.0, np.nan, 30.0, np.nan, 50.0])

print(a)
print("isnan:", np.isnan(a))
print("Normal mean:", np.mean(a))
print("NaN-safe mean:", np.nanmean(a))
print("NaN-safe sum:", np.nansum(a))
print("Remove NaN:", a[~np.isnan(a)])

[10. nan 30. nan 50.]
isnan: [False  True False  True False]
Normal mean: nan
NaN-safe mean: 30.0
NaN-safe sum: 90.0
Remove NaN: [10. 30. 50.]


## 27. Matrix Multiplication

In [53]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise A * B:\n", A * B)
print("\nMatrix multiplication A @ B:\n", A @ B)
print("\nnp.matmul:\n", np.matmul(A, B))

Element-wise A * B:
 [[ 5 12]
 [21 32]]

Matrix multiplication A @ B:
 [[19 22]
 [43 50]]

np.matmul:
 [[19 22]
 [43 50]]


## 28. Linear Algebra

In [54]:
A = np.array([[4.0, 2.0], [1.0, 3.0]])
b = np.array([10.0, 8.0])

print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))
print("Solve Ax=b:", np.linalg.solve(A, b))
print("Eigenvalues and eigenvectors:\n", np.linalg.eig(A))
print("Matrix norm:", np.linalg.norm(A))

Determinant: 10.000000000000002
Inverse:
 [[ 0.3 -0.2]
 [-0.1  0.4]]
Solve Ax=b: [1.4 2.2]
Eigenvalues and eigenvectors:
 EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))
Matrix norm: 5.477225575051661


## 29. Save and Load Arrays

In [56]:
sample = np.array([[1, 2, 3], [4, 5, 6]])

np.save("numpy_sample.npy", sample)
loaded = np.load("numpy_sample.npy")

print(loaded)

[[1 2 3]
 [4 5 6]]


## 30. Mini NumPy Exercise — Student Marks Analysis

In [57]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [95, 88, 92],
    [50, 60, 55]
])

student_averages = marks.mean(axis=1)
subject_averages = marks.mean(axis=0)
top_student = np.argmax(student_averages)

print("Marks:\n", marks)
print("Student averages:", student_averages)
print("Subject averages:", subject_averages)
print("Top student index:", top_student)
print("Students with avg >= 75:", np.where(student_averages >= 75)[0])

Marks:
 [[80 75 90]
 [65 70 72]
 [95 88 92]
 [50 60 55]]
Student averages: [81.66666667 69.         91.66666667 55.        ]
Subject averages: [72.5  73.25 77.25]
Top student index: 2
Students with avg >= 75: [0 2]


## NumPy Quick Revision

Core AIML topics covered:

- Array creation and attributes
- Data types
- Indexing and slicing
- Reshaping and transposing
- Vectorized mathematical operations
- Aggregation and axis
- Broadcasting
- Boolean filtering
- `where` / `select`
- Sorting / unique
- Combining / splitting
- Copy vs view
- Missing values
- Random generation
- Matrix multiplication
- Linear algebra
- Saving/loading arrays